language: scala
jdk: oraclejdk7
sudo: false
scala:
  - 2.11.8
script:
  # - sbt retest
  # - sbt funtests
  - sbt build
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
notifications:
  email:
    - reximkut@gmail.com
cache:
  directories:
  - $HOME/.ivy2/cache
